# Generated by Django 4.1.7 on 2023-04-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='des',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
