# Generated by Django 4.1.7 on 2023-04-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_details_rename_des_person_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='team',
        ),
        migrations.DeleteModel(
            name='details',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='image',
        ),
    ]
